### ISSUE TITLE
Running Problem

### ISSUE THREAD

**Issue by 275901397** [SeongJong-Yoo/structure-from-sherds#2]
Hi @SeongJong-Yoo,

Thanks for sharing your work. I met a problem when running the project. There is a core dump in Eigen
![Screenshot from 2022-06-21 11-16-12](https://user-images.githubusercontent.com/30967295/174711097-95650463-50d2-4c5e-ac68-9adf8a54c50e.png)
.I don't know if this problem is related to the version of gcc or Eigen. Will you share your version info, thanks.

**Comment by SeongJong-Yoo** [comment]
Hello @275901397,

Thank you for having interest my code. 

As I know, for Eigen library any version above 3.1 doesn't matter. In my case, I used 3.3.3 version. 
Also, I built my project under 'Windows' system. The others are not verified. 

Thanks.

Seong Jong Yoo.

**Comment by 275901397** [comment]
Thank you for the your response.@SeongJong-Yoo
